name: Bug Report
description: バグ報告
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: 概要
      description: 発生した問題の説明
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 再現手順
      description: 再現に必要な手順
      placeholder: |
        1. 環境 ...
        2. コマンド ...
        3. 入力 ...
        4. 結果 ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待する結果
  - type: input
    id: version
    attributes:
      label: バージョン
      placeholder: 例) v1.1.0
  - type: input
    id: os
    attributes:
      label: OS/アーキテクチャ
      placeholder: 例) macOS 14 / arm64

