name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@v3.30.2

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j 2

      - name: Package
        shell: bash
        run: |
          set -eux
          OUT_DIR=dist
          mkdir -p "$OUT_DIR"
          NAME=ShinoEditor-${{ runner.os }}-${{ matrix.build_type }}
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            BIN=$(ls build/**/ShinoEditor*.exe | head -n1)
            7z a "$OUT_DIR/$NAME.zip" "$BIN" README.md CHANGELOG.md || powershell Compress-Archive -Path "$BIN","README.md","CHANGELOG.md" -DestinationPath "$OUT_DIR/$NAME.zip"
          else
            BIN=$(ls build/ShinoEditor || true)
            if [[ -z "$BIN" ]]; then BIN=$(ls build/**/ShinoEditor | head -n1); fi
            tar czf "$OUT_DIR/$NAME.tar.gz" -C build "$(basename "$BIN")" -C .. README.md CHANGELOG.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
